services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_auth
    ports:
    - "5434:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: